# spring properties
spring:
  application:
    name: smart-issue-tracker-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/issue_tracker
    username: issue_user
    password: Mpakakos.ogiZwJKhM8Pii76T
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://meet-termite-51.accounts.dev
          jwk-set-uri: https://meet-termite-51.clerk.accounts.dev/.well-known/jwks.json
  # Enable or disable restart explicitly
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java/
  # Enable live reload for development
    live-reload:
      enabled: true
server:
  port: 8081
  servlet:
    context-path: /api
clerk:
  public-key: pk_test_bWVldC10ZXJtaXRlLTUxLmNsZXJrLmFjY291bnRzLmRldiQ
  issuer-uri: https://meet-termite-51.accounts.dev
  jwks-uri: https://meet-termite-51.clerk.accounts.dev/.well-known/jwks.json
  public-keyLong: 
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoCoZNSRH8mjx+BZ4uGCl
      nQyFtHDSk9r9xs/eqBn856neSNstvhd3LZIqIMJ/l0FX4rf9DZfa7ej0u6nQAoHK
      CyiUCBPN7AnTJ7RhZUNsvFLzImPE1cuFxWkfHcS8cQafX3pEff0E/9h6s2zQjBHm
      D66bPVVIL58+7WCOhRy7xD9KkSjbbAJZSa/9pLw1p4x8h2skKJpiES0TXycbHj6J
      H7jKcQxzZxArYO5UwNyNX6xrz5MW47GWngj7QHy1T8MitxvwnzYH0ZuGJ90C/f54
      9OGBtpbEGhaIpwPYMkKyGHTr1AMz5AuPlS7BOGpzuI38KflCymlj7zkmjMyX72lm
      RwIDAQAB
      -----END PUBLIC KEY-----
  backend-api-url: https://api.clerk.com
ai:
  provider: openai # or: claude
  openai:
    base-url: https://api.openai.com
    api-key: ${OPENAI_API_KEY}
    model: gpt-4o-mini
  claude:
    base-url: https://api.anthropic.com
    api-key: ${ANTHROPIC_API_KEY}
    model: claude-3-5-sonnet-latest

# Optional: thread pool tuning for @Async
spring.task.execution:
  pool:
    core-size: 4
    max-size: 8
    queue-capacity: 100
