
// src/main/java/com/example/smarttracker/controllers/AISummaryController.java
package com.smartissuetracker.backend.controller;

import com.smartissuetracker.backend.ai.AiSummaryRequest;
import com.smartissuetracker.backend.ai.AiSummaryResponse;
import com.smartissuetracker.backend.service.AISummaryService;

import lombok.AllArgsConstructor;

import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/ai")
@AllArgsConstructor
public class AISummaryController {

    private final AISummaryService aiSummaryService;

    // Constructor is generated by Lombok's @AllArgsConstructor

    @PostMapping("/summarize")
    public AiSummaryResponse summarize(@RequestBody AiSummaryRequest request) {
        return aiSummaryService.generateSummary(request.getTitle(), request.getSummary());
    }
}
